### ISSUE TITLE
Create MCD and Database

### ISSUE THREAD

**Issue by dachic** [iw-dak/elk-movies#3]

**Comment by kconde2** [comment]
Voici une première version

![diagram](https://user-images.githubusercontent.com/43377621/60747856-a985d600-9f88-11e9-8f4a-5aaff1f9c76a.png)

**Comment by kconde2** [comment]
Pour le genre, on peut avoir : 
- Genre
- Action
- Horreur
- Comedie
- Suspense
- Aventure
- Crime
- Fiction
- Dessin animé
- etc...

**Comment by kconde2** [comment]
Pour les langues on peut avoir : 
- Français
- Anglais
- etc ...

**Comment by dachic** [comment]
Je ne trouve pas l'information sur la "langue" intéressante; 
On a toujours les films en VO + d'autres langues, pas besoin de filtrer sur cette donnée je pense

**Comment by kconde2** [comment]
ok
